# -*- coding: utf-8 -*-
{
    'name': 'Procurement Management',
    'version': '17.0.1.0.0',
    'category': 'Purchase',
    'summary': 'Algerian Public Procurement Procedures Management',
    'description': """
        Manage Algerian public procurement procedures
        (Consultations / Tenders / Competitions)
        compliant with Law n23-12 and Presidential Decree n15-247.
    """,
    'author': 'CACOBATPH',
    'license': 'LGPL-3',
    'depends': ['base', 'purchase', 'contacts', 'mail'],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/sequence_data.xml',
        'data/procurement_data.xml',
        'views/procurement_procedure_views.xml',
        'views/procurement_committee_views.xml',
        'views/procurement_session_views.xml',
        'views/procurement_summons_views.xml',
        'views/procurement_notice_views.xml',
        'views/procurement_publication_views.xml',
        'views/procurement_specs_withdrawal_views.xml',
        'views/procurement_bid_deposit_views.xml',
        'views/procurement_bidder_views.xml',
        'views/procurement_envelope_opening_views.xml',
        'views/procurement_evaluation_views.xml',
        'views/procurement_decision_views.xml',
        'views/procurement_award_views.xml',
        'views/procurement_minutes_views.xml',
        'views/procurement_analytical_sheet_views.xml',
        'views/procurement_service_order_views.xml',
        'views/procurement_order_letter_views.xml',
        'views/procurement_document_views.xml',
        'views/purchase_order_inherit_views.xml',
        'views/menu_views.xml',
        'wizards/wizard_generate_summons_views.xml',
        'wizards/wizard_score_evaluation_views.xml',
        'reports/report_tender_notice.xml',
        'reports/report_tender_notice_arabic.xml',
        'reports/report_provisional_award_notice.xml',
        'reports/report_provisional_award_notice_arabic.xml',
        'reports/report_summons.xml',
        'reports/report_specs_approval_decision.xml',
        'reports/report_award_approval_decision.xml',
        'reports/report_service_order.xml',
        'reports/report_order_letter.xml',
        'reports/report_analytical_sheet.xml',
        'reports/report_specs_withdrawal_register.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
