# -*- coding: utf-8 -*-
from . import procurement_procedure
from . import procurement_committee
from . import procurement_committee_session
from . import procurement_committee_member
from . import procurement_summons
from . import procurement_notice
from . import procurement_publication
from . import procurement_specs_withdrawal
from . import procurement_bid_deposit
from . import procurement_bidder
from . import procurement_envelope_opening
from . import procurement_evaluation
from . import procurement_decision
from . import procurement_award
from . import procurement_minutes
from . import procurement_analytical_sheet
from . import procurement_service_order
from . import procurement_order_letter
from . import procurement_document
from . import purchase_order_inherit
from . import res_partner_inherit
